FROM centos:7.4.1708

RUN yum -y update
RUN yum -y install epel-release
RUN yum -y install octave

#RUN wget http://url/to/latest/epel-release-6-7.noarch.rpm
#RUN yum localinstall epel-release-6-7.noarch.rpm
